language: c

env:
  - AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1 AFL_NO_UI=1
  - AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1 AFL_NO_UI=1 AFL_BENCH_JUST_ONE=1

before_install:
  - sudo apt clean
  - sudo apt update
  - sudo apt install -y libtool libtool-bin automake bison libglib2.0
jobs: 
  include:
    - script:
      - make
      - ./afl-gcc ./test-instr.c -o test-instr
      - mkdir seeds; mkdir out
      - echo "" > seeds/nil_seed
      - timeout --preserve-status 5s ./afl-fuzz -i seeds -o out/ -- ./test-instr
      - cd qemu_mode
      - ./build_qemu_support.sh
      - cd ..
      - gcc ./test-instr.c -o test-no-instr
      - timeout --preserve-status 5s ./afl-fuzz -Q -i seeds -o out/ -- ./test-no-instr
